version: "3.8"

services:
  postgres-db:
    image: postgres:14-alpine
    container_name: chibi_link_postgres_db
    environment:
      POSTGRES_USER: chibiuser
      POSTGRES_PASSWORD: chibipassword
      POSTGRES_DB: chibi_link_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend-api:
    container_name: chibi_link_backend_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7037:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+:8081;http://+:8080"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "Password"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      ConnectionStrings__DefaultConnection: "Host=postgres-db;Port=5432;Database=chibi_link_db;Username=chibiuser;Password=chibipassword;"
      Jwt__Issuer: "https://localhost:7037"
      Jwt__Audience: "https://localhost:7037"
      Jwt__SecretKey: "DAY_LA_MOT_CHUOI_BI_MAT_RAT_DAI_VA_AN_TOAN_HAY_THAY_THE_NO"
    depends_on:
      - postgres-db
    restart: unless-stopped

  frontend-web:
    container_name: chibi_link_frontend_web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend-api
    restart: unless-stopped

volumes:
  postgres_data:
